Revert "Add google's regional domains. (#6870)" (#6872)
This reverts commit 21c9ed69dd728a4bf2f02f1570d3fdf29cb71749.

Looks like this pushed the route length past the limit: 

> Error: Builder returned invalid routes: should NOT be longer than 4096
characters

We'll have to find another way for this.

### Change type

- [x] `bugfix`